# nixpacks.toml

[phases.setup]
# AQUI ESTÁ A MÁGICA: Adicionamos "yt-dlp" na lista do sistema.
# O Railway vai instalar o binário oficial e colocar no PATH global.
nixPkgs = ["nodejs", "python3", "ffmpeg", "yt-dlp"]

[phases.install]
# Instalamos apenas o 'requests' caso seu script antigo precise.
# O yt-dlp já foi instalado na fase de setup acima.
cmds = [
    "npm ci",
    "python3 -m pip install requests"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"