# nixpacks.toml

[phases.setup]
# Instala Node (pro site), Python 3 (pro yt-dlp) e FFmpeg (pra processar midia)
nixPkgs = ["nodejs", "python3", "ffmpeg"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"